export const userInfo = {
  id: "123",
  gitHubUrl: "https://github.com/xiehongchen",
  giteeUrl: "https://gitee.com/xiehongchen",
};

export const tagList = [
  {
    id: 0,
    title: "css",
    number: 12,
  },
  {
    id: 1,
    title: "css",
    number: 12,
  },
  {
    id: 2,
    title: "js",
    number: 16,
  },
  {
    id: 3,
    title: "ts",
    number: 4,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
  {
    id: 5,
    title: "c",
    number: 15,
  },
  {
    id: 6,
    title: "py",
    number: 25,
  },
  {
    id: 7,
    title: "c++",
    number: 5,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
  {
    id: 4,
    title: "java",
    number: 5,
  },
];

export const blogList = [
  {
    id: 1,
    title: "1",
    introduction:
      "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑dsad大大大大adddd啊实打实大师大师d啊实打实大师dddddddddsad撒啊实打实大师大多asdasss",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 2,
    title: "2",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 3,
    title: "3",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 4,
    title: "4",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 5,
    title: "5",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 6,
    title: "6",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 7,
    title: "7",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 8,
    title: "8",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 9,
    title: "9",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 10,
    title: "10",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 11,
    title: "11",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
  {
    id: 12,
    title: "12",
    introduction: "只要卡住这个17毫秒，每隔17毫秒进行操作，就能确保动画丝滑",
    author: "xie",
    imgUrl: "@/assets/vue.svg",
    time: "2000-10-1",
    tag: ["abc", "bda", "dada"],
  },
];

export const classList = [
  {
    id: 1,
    imgUrl: "",
    title: "Java",
    number: 11,
  },
  {
    id: 2,
    imgUrl: "",
    title: "JavaScript",
    number: 11,
  },
  {
    id: 3,
    imgUrl: "",
    title: "Python",
    number: 11,
  },
  {
    id: 4,
    imgUrl: "",
    title: "c++",
    number: 11,
  },
  {
    id: 5,
    imgUrl: "",
    title: "c++",
    number: 11,
  },
  {
    id: 6,
    imgUrl: "",
    title: "c++",
    number: 11,
  },
  {
    id: 7,
    imgUrl: "",
    title: "c++",
    number: 11,
  },
];
